# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(default=None, upload_to='photos'),
            preserve_default=False,
        ),
    ]
