# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171031_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
