# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171110_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
    ]
